language: scala

dist: trusty

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers
    - $HOME/.cache

jdk:
  - openjdk11

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M g8
  - cp -R .git target/g8/.git/
  - cd target/g8
  - echo 'addSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.2.7")' >> project/coverall.sbt
  - sbt ci

  ## Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash)