addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "$sbt_native_packager_version$")
addSbtPlugin("com.github.gseitz"         % "sbt-release"         % "$sbt_release_version$")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "$sbt_scoverage_version$")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "$sbt_scalafmt_version$")
addSbtPlugin("org.wartremover"           % "sbt-wartremover"     % "$sbt_wartremover_version$")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "$sbt_tpolecat_version$")
