version: '3'
services:

  service:
    restart: always
    image: "$name_normalized$:latest"
    environment:
      APPLICATION_HTTP_HOST: "0.0.0.0"
      APPLICATION_HTTP_PORT: 9000
      LOG_LEVEL: "INFO"
      MONGODB_URI: "mongodb://mongodb:27017/"
    ports:
      - 9000:9000
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./mongo/data:/data/db
